#!/bin/sh
[ -n "$CREDSAFE_DEBUG" ] && set -x
set -eu

list_commands () {
  IFS=:
  for path in $PATH; do
    for command in "${path}/credsafe-"*; do
      [ -e "$command" ] || [ -L "$command" ] || continue
      echo "${command##*credsafe-}"
    done
  done
}

list_commands | sort | uniq
