#!/bin/sh
[ -n "$CREDSAFE_DEBUG" ] && set -x
set -eu

credsafe init -c

if [ $# -ne 1 ]; then
  credsafe help user
  exit 1
fi

name=$1

credsafe checkusername "$name"

if ! credsafe user get "$name" >/dev/null; then
  error "User $name doesn't exist"
  exit 1
fi

touch "$CREDSAFE_USERS"
sed -E -i '' -e "/^$name[[:space:]]/d" "$CREDSAFE_USERS"

status "Removed user $name"
